### ISSUE TITLE
Figures are not generated in folder or summary.pdf

### ISSUE THREAD

**Issue by Shen-Jing** [kamimrcht/ELECTOR#12]
Hello,
Sorry to bother you.

In README.md it mentioned:
> These results are recalled in out/log and out/summary.pdf along with figures:

But there are only 3 parts & tables (summary, remapping, assembly) in my summary.pdf.

#### My command

```python
python3 -m elector -threads 16 -uncorrected Yeast_d60 -reference reproduce_manuscript_results/references/Yeast.fasta -corrected Yeast_d60_LoRMA.fasta -output Yeast_d60_LoRMA -split -remap -assemble -simulator simlord -corrector lorma
```

Excuse me, I would like to ask what I did wrong (how to generate pictures).

Thank you!

**Comment by Shen-Jing** [comment]
After traced the code, I found `ggplot2` is one of the reason.

I use `R` and:
```r
install.packages("ggplot2")
```

Now, "plot_size_distribution.png" is successfully generated.

But there is still **no** recall and precision figure. 😥  


### My log
![image](https://user-images.githubusercontent.com/9480153/114990034-b0b27580-9eca-11eb-8ee5-7303d8826933.png)

### My folder content
![image](https://user-images.githubusercontent.com/9480153/114990192-db9cc980-9eca-11eb-9989-0393c0ea9099.png)

**Comment by morispi** [comment]
I pushed a fix and tried to reproduce the issue, but the plots were correctly generated for me.

Could you pull and try to run again, see if it works for you? Maybe you could avoid running the whole experiment again, and just to a `head -100 Yeast_d60_LoRMA.fasta > test.fasta`

And then run : `python3 -m elector -threads 16 -uncorrected Yeast_d60 -reference reproduce_manuscript_results/references/Yeast.fasta -corrected test.fasta -output TestPlots -split -simulator simlord -corrector lorma`

That would only assess the 50 first reads, and be much faster, since we only want to see why the plots don't get generated here.

Best,
Pierre

**Comment by Shen-Jing** [comment]
Hello Pierre,

It works for me, thanks your fix!

Jing
